vich_uploader:
    db_driver: orm

    mappings:
        service_images:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        tool_images:
            uri_prefix: /uploads/tools
            upload_destination: '%kernel.project_dir%/public/uploads/tools'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        logement_images:
            uri_prefix: /uploads/logements
            upload_destination: '%kernel.project_dir%/public/uploads/logements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
